# Logit-modell {#Chapter-3}

```{css, echo=FALSE}
p {
  text-align: justify;
}
```


```{r package, include=FALSE, warning=FALSE}
library(tidyverse)
library(pROC)
library(ggplot2)
library(gt)
library(car)
library(dplyr)
library(HH)
library(lmtest)
library(sandwich)
```


```{r data, include=FALSE, warning=FALSE, message = F}
#Adatok megtisztítása
raw <- vroom::vroom('latestdata.csv', col_types = cols(
  ID = col_character(),
  age = col_character(),
  sex = col_character(),
  city = col_character(),
  province = col_character(),
  country = col_character(),
  latitude = col_double(),
  longitude = col_double(),
  geo_resolution = col_character(),
  date_onset_symptoms = col_character(),
  date_admission_hospital = col_character(),
  date_confirmation = col_character(),
  symptoms = col_logical(),
  lives_in_Wuhan = col_logical(),
  travel_history_dates = col_character(),
  travel_history_location = col_character(),
  reported_market_exposure = col_logical(),
  additional_information = col_character(),
  chronic_disease_binary = col_logical(),
  chronic_disease = col_logical(),
  source = col_character(),
  sequence_available = col_logical(),
  outcome = col_character(),
  date_death_or_discharge = col_logical(),
  notes_for_discussion = col_logical(),
  location = col_character(),
  admin3 = col_character(),
  admin2 = col_character(),
  admin1 = col_character(),
  country_new = col_character(),
  admin_id = col_double(),
  data_moderator_initials = col_character(),
  travel_history_binary = col_logical()
)) 

raw %>% 
  select(outcome, age, sex, country, chronic_disease_binary, latitude, longitude, date_confirmation        ) %>% 
  mutate(
    continent = countrycode::countrycode(country, origin = 'country.name', destination = 'continent'),
    date = lubridate::dmy(date_confirmation),
    age = ifelse(str_detect(age, '-'), as.numeric(gsub("([0-9]+).*$", "\\1", age)) + 5, age),
    age = as.numeric(age)
  ) %>% 
  mutate( # cleaning the depedent var
    outcome = case_when(
      outcome == 'death' ~ 'died',
      outcome == 'died' ~ 'died', 
      outcome == 'Death' ~ 'died',
      outcome == 'dead' ~ 'died',
      outcome == 'Dead' ~ 'died',
      outcome == 'Died' ~ 'died',
      outcome == 'Deceased' ~ 'died',
      outcome == 'discharge' ~ 'survived',
      outcome == 'discharged' ~ 'survived',
      outcome == 'Discharged' ~ 'survived',
      outcome == 'Discharged from hospital' ~ 'survived',
      outcome == 'recovered' ~ 'survived',
      outcome == 'released from quarantine' ~ 'survived',
      outcome == 'recovered' ~ 'survived',
      outcome == 'Recovered' ~ 'survived',
      outcome == 'Recovered' ~ 'survived',
      outcome == 'Recovered' ~ 'survived',
      T ~ 'NA'
    )
  ) %>% 
  filter(outcome != 'NA') %>% 
  mutate(
    died = outcome == 'died'
  ) %>% select(-outcome, -date_confirmation) %>% 
  {dat <<- .; .}
dat <- na.omit(dat)
```

Egyesével regresszálva a változókat az alábbi grafikonokat kapjuk
```{r}
logit_age <- glm(died~age, data=dat2, family = binomial(logit))
summary(logit_age)
```


Logit modell kalibrálása az összes tisztított és korábban bemutatott változóra

```{r}
#Országok szintjén magas VIF mutató látható
logit <- glm(died~., data=dat, family=binomial(logit))
summary(logit)
vif(logit)

#Outlierek leszűrése
dat <- dat[abs(rstudent(logit))<3, ]

#Országok kihagyásával mérséklődik a VIF mutató
logit2 <- glm(died~.-country -longitude -latitude, data=dat, family=binomial(logit))
summary(logit2)
vif(logit2)

#Amerikát összevonva Ázsiával a VIF mutatók lecsökkennek
dat <- na.omit(dat)
dat[dat$continent=="Americas", "continent"] <- "Asia"

logit3 <- glm(died~.-country -longitude -latitude, data=dat, 
             family=binomial(logit))
summary(logit3)
vif(logit3)

#Sajnos még nem lineáris a modellünk, a változókat át kell alakítani
resettest(logit3)
crPlots(logit3)

```


```{r}
#Először a dátumot vesszük ki a magyarázóváltozók közül, mivel az értelmezése nehézkes,
#majd az életkor változóját alakítjuk át a linearitás eléréséhez
logit4 <- glm(died~.-country -date -latitude -longitude +I(1/(0.1+age)), 
              data=dat, family=binomial(logit))
summary(logit4)
vif(logit4)
resettest(logit4)
crPlots(logit4)
```

```{r}


logit5 <- glm(died~.-country -age +I(1/(0.1+age)) -date -latitude -longitude, data=dat, 
              family=binomial(logit))
summary(logit5)
vif(logit5)
resettest(logit5)

#Elhagyható a magyarázóváltozók közül szinte az összes
linearHypothesis(logit5, c("I(1/(0.1 + age))=0", "continentEurope=0", "continentAsia=0", "continentOceania=0"))

logit6 <- glm(died~.-country -age -date -latitude -longitude, data=dat, 
              family=binomial(logit))
summary(logit6)
resettest(logit6)

exp(coef(logit6))
```

```{r}
deathval <- predict(logit6, dat, type="response")
dat$deathval <- deathval
dat$becsult <- ifelse(deathval>0.5, "TRUE", "FALSE")
xtabs(~died+becsult, data=dat)
sum(dat$died==dat$becsult)/nrow(dat)
```


```{r}
ROCgorbe <- roc(dat$died~dat$deathval)
plot(ROCgorbe)
2*auc(ROCgorbe)-1

ytengely <- ROCgorbe$sensitivities
xtengely <- ROCgorbe$specificities
kuszob <- ROCgorbe$thresholds
seged <- data.frame(kuszob, xtengely, ytengely)
table(dat$died)

seged$koltseg <- 4046*(1-xtengely)+1302*(1-ytengely)
ggplot(seged, aes(x=kuszob, y=koltseg))+geom_point()+geom_smooth()+xlim(0,1)
```


